spring.application.name=TTGT2-THPT

spring.datasource.url=jdbc:mysql://localhost:3306/onthithpt?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Bangkok
spring.datasource.username=root
spring.datasource.password=6122002
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

